nelmio_api_doc:
    documentation:
        info:
            title: Dog Walker
            description: Register your dog and have fun!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/dog
