version: "3"

services:
    dog-walker-php:
        build: .
        image: moriorgames/dog-walker-php
        restart: unless-stopped
        env_file:
        - .env.local
        container_name: dog_walker_php
        environment:
        - PORT=8081
        ports:
        - "8081:80"
        volumes:
        # Comment next line to work locally sync files between your host and docker container
        - "${PWD}/:/app"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./docker/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
        tty: true

    dog-walker-php-2:
        build: .
        image: moriorgames/dog-walker-php
        restart: unless-stopped
        env_file:
        - .env.local
        container_name: dog_walker_php_2
        environment:
        - PORT=8082
        ports:
        - "8082:80"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./docker/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
        tty: true

    # Depends on backend MYSQL
    mysql:
        image: mysql:5.7
        env_file: mysql/mysql.env
        container_name: dog_walker_db
        volumes:
        - "${PWD}/mysql/init:/docker-entrypoint-initdb.d/"
        ports:
        - "3308:3306"

    nginx:
        image: nginx
        container_name: dog_walker_nginx
        ports:
        - "8080:80"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"

networks:
    default:
        external:
            name: dev
