DogWalker\Domain\Entity\Dog:
    type: entity
    table: dog
    id:
        uuid:
            type: string
            generator:
                strategy: NONE
    fields:
        owner:
            type: string
            nullable: false
        name:
            type: string
            nullable: false
        breed:
            type: string
            nullable: false
        age:
            type: integer
            nullable: false
        createdAt:
            type: datetime
            nullable: false
        updatedAt:
            type: datetime
            nullable: false
