register_dog:
    path: /dog
    controller: DogWalker\UI\Symfony\Controller\DogController::registerDog
    methods: POST

get_dog_details:
    path: /dog/{dog_uuid}
    controller: DogWalker\UI\Symfony\Controller\DogController::getDogDetails
    methods: GET

click_me:
    path: /click_me
    controller: WebFront\UI\Symfony\Controller\ClickMeController::handle
    methods: GET

health:
    path: /health
    controller: WebFront\UI\Symfony\Controller\HealthController::handle
    methods: GET

index:
    path: /
    controller: WebFront\UI\Symfony\Controller\IndexController::handle
    methods: GET
