home:
    path: /
    controller: DogWalker\UI\Symfony\Controller\IndexController::home
    methods: GET

index_ping:
    path: /ping
    controller: DogWalker\UI\Symfony\Controller\IndexController::ping
    methods: GET

register_dog:
    path: /dog
    controller: DogWalker\UI\Symfony\Controller\DogController::registerDog
    methods: POST

get_dog_details:
    path: /dog/{dog_uuid}
    controller: DogWalker\UI\Symfony\Controller\DogController::getDogDetails
    methods: GET

get_click_me:
    path: /click_me
    controller: DogWalker\UI\Symfony\Controller\ClickMeController::get
    methods: GET
