dog_register:
    path: /dog
    controller: DogWalker\UI\Controller\RegisterDogController::handle
    methods: POST

dog_details:
    path: /dog/{dog_uuid}
    controller: DogWalker\UI\Controller\DogDetailsController::handle
    methods: GET

click_me:
    path: /click_me
    controller: WebFront\UI\Controller\ClickMeController::handle
    methods: GET

health:
    path: /health
    controller: WebFront\UI\Controller\HealthController::handle
    methods: GET

index:
    path: /
    controller: WebFront\UI\Controller\IndexController::handle
    methods: GET
