parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    DogWalker\:
        resource: '../src/DogWalker/*'
        exclude: '../src/DogWalker/UI/{DependencyInjection,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    DogWalker\UI\Controller\:
        resource: '../src/DogWalker/UI/Controller'
        tags: ['controller.service_arguments']

    WebFront\UI\Controller\:
        resource: '../src/WebFront/UI/Controller'
        tags: ['controller.service_arguments']

    # Custom services
    app.dog_repository:
        class: DogWalker\Infrastructure\Repository\DoctrineDogRepository

    # Custom bindings
    DogWalker\Domain\Repository\DogRepository: '@app.dog_repository'

    #Event Subscribers bindings
    Symfony\Component\EventDispatcher\EventSubscriberInterface:
        class: SharedKernel\UI\EventSubscriber\BeforeActionSubscriber
