parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    DogWalker\:
        resource: '../src/DogWalker/*'
        exclude: '../src/DogWalker/UI/Symfony/{DependencyInjection,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    DogWalker\UI\Symfony\Controller\:
        resource: '../src/DogWalker/UI/Symfony/Controller'
        tags: ['controller.service_arguments']

    WebFront\UI\Symfony\Controller\:
        resource: '../src/WebFront/UI/Symfony/Controller'
        tags: ['controller.service_arguments']
